### ISSUE TITLE
[percep] CIRC Panorama

### ISSUE THREAD

**Issue by qhdwight** [umrover/mrover-workspace#1053]
- Stitch together multiple images to create a panorama, basically what the iPhone can do in the Camera app
- Don't reinvent the wheel, find out if someone has done this with the ZED yet
- Apparently 442 has some content on that so se if you can check that out

**Comment by niwhsa9** [comment]
it was actually literally one of the homeworks they made us do. I'd highly recommend **NOT** trying to write it yourself from scratch (compute homography via DLT). The better way is to use photoshop or something. If you absolutely have to do it programmatically try this: https://docs.opencv.org/4.x/d8/d19/tutorial_stitcher.html.
