### ISSUE TITLE
Add GPU Capabilities to Obstacle Detection

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#337]
Use the GPU Euclidean Cluster Extraction algorithm and see if there are any performance gains associated with this method. Checkout this [file ](https://github.com/PointCloudLibrary/pcl/blob/master/gpu/examples/segmentation/src/seg.cpp)for an example on how to implement it. Add it to the pcl.cpp file

Also, check out this power point to gain a basic understanding of CUDA and memory allocation on the GPU: http://developer.download.nvidia.com/compute/developertrainingmaterials/presentations/cuda_language/Introduction_to_CUDA_C.pptx

We are going to:
- [x] Read data from ZED to GPU
- [x] Write our own passthrough filter cuda file
- [x] Implement the point cloud library cuda ransac function
- [x] Implement the pcl euclidian cluster function
- [x] write our own center path function
- [x] ACHIEVE STUNNING PERFORMANCE
- [x] DOMINATE COMPETITION!!!!

**Comment by niwhsa9** [comment]
code under development here https://github.com/umrover/perception-gpu-obs-detector

**Comment by niwhsa9** [comment]
🥳
