### ISSUE TITLE
Add ZED camera gimbal functionality to simulator

### ISSUE THREAD

**Issue by atguimond** [umrover/mrover-workspace#471]
- Transferring rover search spin from spinning the wheels to spinning the camera gimbal
- Gimbal located on the front of the ebox
- Field of vision changes with gimbal
- Eliminating the need for spinning but not turning

**Comment by amverni** [comment]
@atguimond Can you add a link to the PR and line number where the new/changed LCM message is allowing `jetson/nav` to control the gimbal? Also, please add the relevant labels and project for this issue.

**Comment by atguimond** [comment]
This code is in testing stages so there is no PR yet. We were waiting until we could test it. The code is currently on this branch: https://github.com/ankithu/mrover-workspace/tree/gimbal-nav

**Comment by amverni** [comment]
Got it. To complete the loop, [this](https://github.com/ankithu/mrover-workspace/blob/gimbal-nav/rover_msgs/GimbalCmd.lcm) is the interface we will be using to control the gimbal.

**Comment by atguimond** [comment]
We created a different lcm message [here](https://github.com/ankithu/mrover-workspace/blob/gimbal-nav/rover_msgs/ZedGimbalCmd.lcm).

**Comment by amverni** [comment]
Why are we creating a new LCM? Can we not reuse the old one? If not, what is the old one being used for and can we change it?

**Comment by atguimond** [comment]
We created the new one to keep things simple and streamlined. I have no idea what the old one is for (probably another gimbal) and I did not want to step on anyone's toes if someone else is still using it. We also added a new lcm that ESW is publishing and nav is listening to called ZedGimbalData.lcm that sends the same stuff to us that we are sending back.

**Comment by amverni** [comment]
Can you clarify what the power means? In other words. If I, acting as the simulator, get a power or `x`, what should I do with that? How would I interpret that? What range of values are valid? How fast does a power value of `x` move the gimbal (might not be able to answer that one)?

**Comment by atguimond** [comment]
We refactored the code to make it easier in terms of yaw [here](https://github.com/ankithu/mrover-workspace/blob/gimbal-nav-no-pid/rover_msgs/ZedGimbalCmd.lcm). 0 degrees is straight ahead, +90 is 90 degrees clockwise, and -90 is 90 degrees counterclockwise, and so on. The range of valid values would be from -180 to +180.
