### ISSUE TITLE
RANSAC Plane Detects largest plane not flattest

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#473]
Don't worry about the title. The first thing you should focus on is that when RANSAC runs it doesn't always detect the ground plane, but instead detects the largest plane. Your job will be to understand the RANSAC algorithm and tune it so that it detects the ground plane and not the largest plane. An example of this can be found by running a test with the main perception-files folder. There will be an image of a hill and we detect the hill as a large ground plane as opposed to an obstacle. For debugging purposes change the parameter in RNASACSegmentation function from "remove" to "blue". Make sure you check out the pcl readthedocs website which can be accessed from their main website at pointclouds.org to really understand the RANSAC function.

**Comment by niwhsa9** [comment]
No longer detects the hill for the most part. I will try to test it with the ZED too to see how reliable it is out in the wild. I'm guessing we will adjust epsilon a bit after more testing on the actual rover.
