### ISSUE TITLE
Create auton integration test setup doc

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#554]
When running the auton suite a fairly intensive setup process must occur in order to ensure the correct code is running on the correct computer, that is interacting properly with all the various auton sensors. We want to detail this process in a step by step document, so that others that are not familiar with the setup are able to carry it out, and have a list of items they must obtain in order to successfully run the test.

**Comment by raytitan** [comment]
This ought to be a good starting point
[November auton integration test agenda](https://docs.google.com/document/d/11QA3uMPI2vjlVy21N6UoTRqBwsR__8P4tCYqFFTcOQE/edit?usp=sharing)
