### ISSUE TITLE
Configure Jarvis to compile CUDA code

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#560]
Perception will receive a significant performance boost from utilizing the GPU. Jarvis must therefore, be able to use NVCC in meson to compile CUDA kernels. Some modifications to Jarvis may be necessary in order for this to happen.

**Comment by niwhsa9** [comment]
Code under development here: https://github.com/umroverPerception/mrover-workspace/tree/gpuObsDetector

**Comment by niwhsa9** [comment]
done
