### ISSUE TITLE
[percep] Add program pause capabilities on viewer click

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#668]
When we run our code in debug mode it is very handy to be able to pause the program at a point to further analyze what is being processed. We would like to add the capability to be able to click a viewer or another window to pause the program and be able to step through it frame by frame with the arrow keys. We also want the 3D viewers to stay live, so these will need to be run in a separate thread that is not paused.

**Comment by niwhsa9** [comment]
i implemented this in the GPU Obs detector in PCL viewer mode, so its a copy/paste job. Good first issue for someone
