### ISSUE TITLE
[percep] ZED SDK throws compiler warnings

### ISSUE THREAD

**Issue by mmartin4972** [umrover/mrover-workspace#670]
It is very difficult to debug a program when most of the compiler output is meaningless garbage and it also doesn't look very good when you compile your code and get a bajillion warnings. Please find a way to supress the ZED SDK warnings that way Perception code compiles nicely without a ton of garbage output

**Comment by niwhsa9** [comment]
see: https://stackoverflow.com/questions/1867065/how-to-suppress-gcc-warnings-from-library-headers

I'm not sure if Meson supports this though with include_dirs
