### ISSUE TITLE
Implement a unit-testing framework on known keyframes

### ISSUE THREAD

**Issue by niwhsa9** [umrover/mrover-workspace#750]
- Add a new OperationMode to obs_detector.cu, OperationMode::TEST
- Have ObsDetector launch a test() member function from its constructor when its operation mode is TEST
- Assume that you are given an array of GPU_Cloud's, as well as a vector of ObsReturn's that contain the ground truth for the detections(Sean should be familiar with that data)
- Run the GPU_Clouds 1 by 1 through our detection pipeline to get the ObsReturn struct the detector computed and compare to the ground truth
- For each entry in the ground truth, loop thru the detections by the pipeline and see if theres a non-zero IoU for any of them, if so, consider that as a detection of the obstacle and average that IoU with any other non-zero IoU's for that ground truth obstacle
- If there are no non-zero IoU's, that obstacle is undetected
- Return average accuracy across all obstacles and all input point clouds

**Comment by Seanathan546** [comment]
Number of obstacles found and time the actual obs_detector portion - make a class for unit_testing. Also, if there is extra time try to implement something on an object-to-object basis (not urgent though)
