### ISSUE TITLE
Visualizer Free-Look

### ISSUE THREAD

**Issue by niwhsa9** [umrover/mrover-workspace#772]
I'd like to have a 'free look/move' mode that behaves like a first person video game. We can move in the scene with WASD and pan around the camera with the mouse.

In addition, I want users to be able to click on a point and the visualizer to draw a dot there, as well as report its coordinates  in the command line. This will be useful for generating ground truth for our unit-test framework.

**Comment by Seanathan546** [comment]
@niwhsa9 Yeah if we could generate coordinates of points we could use them to make Obstacle structs for ground truth
