### ISSUE TITLE
Fix State Machine getting stuck(?)

### ISSUE THREAD

**Issue by zwgold** [umrover/mrover-workspace#781]
If we don't give up on the state machine: One of our test files exposed a potential bug in the auton_integration, where the rover is stuck between 2 states. A potential logic bug in our code, might be tied to issues during integration testing.

Additionally: Investigate if the issue is in the auton_integration or main branch? (Test the unit test on main)

**Comment by aswarner** [comment]
[test_case_2021-11-07T19_32_10.155Z.zip](https://github.com/umrover/mrover-workspace/files/7492995/test_case_2021-11-07T19_32_10.155Z.zip)
