### ISSUE TITLE
project 3d detections on to image for auton GUI

### ISSUE THREAD

**Issue by niwhsa9** [umrover/mrover-workspace#819]

**Comment by arschallwig** [comment]
First discussion notes: 
- 3D data would be difficult to compress/transmit -> project onto a top and front plane
- These frames will be easier to compress and transmit

**Comment by qhdwight** [comment]
The plan is to stream it, correct?

**Comment by niwhsa9** [comment]
yep, as real-time as possible. You can encode for h265 in Gstreamer maybe

**Comment by niwhsa9** [comment]
the other way to go about this is to send the full 3D clouds and have a webGL viewer on the other end to display. But I worry that the cloud resolution might be too large like Andrew mentioned, and compression while preserving the spatial structure seems complicated.

**Comment by qhdwight** [comment]
For the image option, we could use OpenCV https://answers.opencv.org/question/202017/how-to-use-gstreamer-pipeline-in-opencv/ to stream

**Comment by niwhsa9** [comment]
Yeah I've used that before actually. That'll work.
