### ISSUE TITLE
[Nav] Add Wait time after a final driving destination is reached

### ISSUE THREAD

**Issue by aswarner** [umrover/mrover-workspace#829]
- implement a new state after the rover has "arrived" at its final waypoint for NON SEARCH LEGS ONLY (legs 1-3)
- wait for a configurable time period to allow gps to acquire best fix/position reading
- determine whether we have arrived. DONE if not, DRIVE else

**Comment by zwgold** [comment]
Closing after discussion that GPS lag is not an issue
