### ISSUE TITLE
Depth camera research

### ISSUE THREAD

**Issue by niwhsa9** [umrover/mrover-workspace#961]
Need to identify and purchase depth cam. Thinking Realsense 435i but lets explore all options. Look for active IR and integrated IMU

**Comment by qhdwight** [comment]
ZED 2i bought due to:
- Active development and support by ZED, Intel Realsense division being shutdown, claim "will still support" but skeptical
- Better detection distance
- Water & dust resistant IP66
- Built in magnetometer + other sensors
- Code already with ZED SDK
